# Generated by Django 5.0.4 on 2024-04-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='club',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
