# Generated by Django 5.0.4 on 2024-04-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='description',
            new_name='itinerary',
        ),
    ]
